package com.example.fittracker;

public class ConstantUtils {
    public static final int ONE = 1;
    public static final String EMPTY = "";
    public static final int ZERO = 0;
    public static final int NEGATIVE_ONE = -1;
    public static final String DB_USER_TABLE = "user_table";
    public static final String EMAIL_FORMAT = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
    public static final String USER_PREFERENCES_ID = "user_id";
    public static final String USER_PREFERENCES_STEPS = "user_steps";
    public static final String USER_PREFERENCES = "user_preferences";
    public static final String RETURN_CONTENT_TYPE = "application/octet-stream";
    public static final String RETURN_GMAIL_NAME = "ByteArrayDataSource";
    public static final String OUTPUT_STREAM_EXCEPTION = "Not supported";
    public static final String EMAIL_SENDER = "pps2019.cg@gmail.com";
    public static final String PASSWORD_SENDER = "poporunga";
    public static final String EMAIL_SUBJECT = "This is your signup information";
    public static final String SENDMAIL_LOG = "SendMail";
    public static final String DATAHANDLER_TYPE = "text/plain";
    public static final Character COMA = ',';
    public static final int LOCATION_REQUEST_CODE = 1;
    public static final String WEATHER_UNITS = "metric";
    public static final String PNG_EXTENSION = ".png";
    public static final String CELSIUS_EXTENSIONS = "ºC";
    public static final int WEATHER_ICON_DIMENSION = 100;
    public static final String PERCENT = "%";
    public static final String PASCALS = "HPa";
    public static final int MARVEL_API_LIMIT = 10;
    public static final int MARVEL_IMAGE_SMALL_DIMENSION = 200;
    public static final int MARVEL_IMAGE_LARGE_DIMENSION = 400;
    public static final String DOT = ".";
    public static final String DEFAULT_AVATAR_URL = "http://i.annihil.us/u/prod/marvel/i/mg/c/e0/535fecbbb9784.jpg";
    public static final int WORKOUT_API_LIMIT = 32;
    public static final String WORKOUT_API_FORMAT = "json";
    public static final Character SLASH = '/';
    public static final int WORKOUT_IMAGEDESCRIPTION_OFFSET = 5;
    public static final Character HYPHEN = '-';
    public static final Character SPACE = ' ';
    public static final int FOUR = 4;
    public static final int EXERCISE_IMAGE_SMALL_DIMENSION = 200;
    public static final int EXERCISE_IMAGE_LARGE_DIMENSION = 400;
    public static final float STEPS_TO_KILOMETERS = 0.0008F;
    public static final float STEPS_TO_CALORIES = 0.04F;
    public static final String FLOAT_FORMAT = "%.2f";
}
